## Preprocessing

In [338]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
# application_df = pd.read_csv('saved_csv.csv')
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [339]:
application_df.to_csv('saved_csv.csv')

In [340]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN','NAME','SPECIAL_CONSIDERATIONS'], inplace=True)

In [341]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
STATUS                 2
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [342]:
# Look at APPLICATION_TYPE value counts for binning
val_counts = application_df.APPLICATION_TYPE.value_counts()
val_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [343]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       27
T12         27
Name: APPLICATION_TYPE, dtype: int64

In [344]:
# Look at CLASSIFICATION value counts for binning
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [345]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df.CLASSIFICATION.value_counts().loc[lambda x: x>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [346]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = []
class_dict = application_df.CLASSIFICATION.value_counts().to_dict()
for class_ in class_dict:
    if class_dict[class_] < 50:
        classifications_to_replace.append(class_)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      391
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
Name: CLASSIFICATION, dtype: int64

In [347]:
application_df.dtypes

APPLICATION_TYPE    object
AFFILIATION         object
CLASSIFICATION      object
USE_CASE            object
ORGANIZATION        object
STATUS               int64
INCOME_AMT          object
ASK_AMT              int64
IS_SUCCESSFUL        int64
dtype: object

In [348]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies = pd.get_dummies(data = application_df, columns=['APPLICATION_TYPE', 'AFFILIATION','CLASSIFICATION','USE_CASE','ORGANIZATION','INCOME_AMT'])
app_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,108590,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1,6692,1,0,0,0,0,0,1,0,...,1,0,0,1,0,0,0,0,0,0
4,1,142590,1,0,0,0,0,0,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
34295,1,5000,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
34296,1,5000,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
34298,1,36500179,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0

In [349]:
x.shape

(34299, 47)

In [350]:
x

array([[       1,     5000,        0, ...,        0,        0,        0],
       [       1,   108590,        0, ...,        0,        0,        0],
       [       1,     5000,        0, ...,        0,        0,        0],
       ...,
       [       1,     5000,        0, ...,        0,        0,        0],
       [       1,     5000,        0, ...,        0,        0,        0],
       [       1, 36500179,        0, ...,        0,        0,        0]],
      dtype=int64)

In [351]:
# Split our preprocessed data into our features and target arrays
y = app_dummies['IS_SUCCESSFUL'].values
x = app_dummies.drop(columns=['IS_SUCCESSFUL'],axis = 1).values

In [352]:

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [353]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [358]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 4
hidden_nodes_layer3 = 3

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="tanh")
)
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='tanh'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_76 (Dense)            (None, 8)                 440

 dense_77 (Dense)            (None, 4)                 36

 dense_78 (Dense)            (None, 3)                 15

 dense_79 (Dense)            (None, 1)                 4

=================================================================
Total params: 495
Trainable params: 495
Non-trainable params: 0
_________________________________________________________________

In [359]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [360]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 1s 775us/step - loss: 0.6112 - accuracy: 0.6893
Epoch 2/50
804/804 [==============================] - 1s 802us/step - loss: 0.5614 - accuracy: 0.7224
Epoch 3/50
804/804 [==============================] - 1s 797us/step - loss: 0.5557 - accuracy: 0.7249
Epoch 4/50
804/804 [==============================] - 1s 826us/step - loss: 0.5531 - accuracy: 0.7266
Epoch 5/50
804/804 [==============================] - 1s 815us/step - loss: 0.5510 - accuracy: 0.7271
Epoch 6/50
804/804 [==============================] - 1s 855us/step - loss: 0.5498 - accuracy: 0.7267
Epoch 7/50
804/804 [==============================] - 1s 817us/step - loss: 0.5489 - accuracy: 0.7286
Epoch 8/50
804/804 [==============================] - 1s 813us/step - loss: 0.5481 - accuracy: 0.7291
Epoch 9/50
804/804 [==============================] - 1s 820us/step - loss: 0.5474 - accuracy: 0.7311
Epoch 10/50
804/804 [==============================] - 1s 809us/step - loss: 0.5469 - accuracy: 0.7300
Epoch 11/50
804/804 [==============================] - 1s 806us/step - loss: 0.5464 - accuracy: 0.7297
Epoch 12/50
804/804 [==============================] - 1s 865us/step - loss: 0.5463 - accuracy: 0.7301
Epoch 13/50
804/804 [==============================] - 1s 809us/step - loss: 0.5459 - accuracy: 0.7304
Epoch 14/50
248/804 [========>.....................] - ETA: 0s - loss: 0.5502 - accuracy: 0.7272

KeyboardInterrupt:

In [357]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

KeyboardInterrupt:

In [ ]:
# Export our model to HDF5 file

from keras.models import load_model
nn.save("NeuralNetwork.h5")
loaded_model = load_model("NeuralNetwork.h5")
loss, accuracy = loaded_model.evaluate(test_data, test_targets)

NameError: name 'test_data' is not defined